#!/bin/bash

# this from http://code.google.com/p/lsyncd/wiki/HowToExecAfter
# execute rsync just like it would have been done directly,
# but save the exit code
IFS=
err=0
#/usr/bin/rsync $@ || err=$?

#unison lipsync $@ || err=$?
#unison lipsync $@ || err=$?
#unison lipsync -debug all || err=$?
unison lipsync || err=$?
#unison $@ || err=$?

# this writes source -> destination details to /var/log/lipsyncd.log
eval src=\${$(($# - 1))}
eval dst=\${$#}
echo "$src -> $dst" >> /var/log/lipsyncd.log || true

# returns the exit code of rsync to lsyncd
exit $err

