#!/bin/sh -e
# Distributed under the terms of the BSD License.
# Copyright (c) 2011 Phil Cryer phil.cryer@gmail.com
# Source https://github.com/philcryer/lipsync
 
USER_NAME=LSUSER
LOCAL_DIR=LSLOCDIR
REMOTE_HOST=LSREMSERV
REMOTE_DIR=LSREMDIR
SSH_PORT=LSPORT
