#!/bin/sh
### BEGIN INIT INFO
# Provides:          lipsyncd
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: a service that provides command-line, Dropbox like syncing


### END INIT INFO
# /etc/init.d/lipsyncd start and stop lipsyncd daemon 
# Phil Cryer, phil@cryer.us

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/lipsyncd
CONFIG="/etc/lipsyncd.conf.xml"
NAME=lipsyncd
DESC="daemon lipsyncd"

set -e

# Check if DAEMON binary exist
test -f $DAEMON || exit 0

if [ -f "/etc/default/lipsyncd" ]; then
     . /etc/default/lipsyncd
fi

#ARGS="-c $CONFIG -s /var/lib/lipsyncd/lipsyncd.state"

case "$1" in
  start)
	echo -n "Starting $DESC: "
	echo -n "$NAME"
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON > /dev/null 2>&1 -- $ARGS
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: "
	echo -n "$NAME"
	start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON  > /dev/null 2>&1
	echo "."
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|syntax}" >&2
	exit 1
	;;
esac

exit 0
